# Generated by Django 5.2.6 on 2025-09-11 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost_per_gram', models.DecimalField(decimal_places=2, max_digits=6)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Maintenance', 'Maintenance')], default='Available', max_length=50)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stl_file', models.FileField(upload_to='stl_files/')),
                ('weight_grams', models.FloatField()),
                ('estimated_time', models.DurationField(help_text='Estimated print time (hh:mm:ss)')),
                ('status', models.CharField(choices=[('Q', 'Queued'), ('P', 'In Progress'), ('C', 'Completed'), ('F', 'Failed')], default='Q', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrintHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.printer')),
                ('print_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.printjob')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
