# Generated by Django 5.2.6 on 2025-09-11 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='printers',
            field=models.ManyToManyField(blank=True, related_name='print_jobs', to='my_app.printer'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Maintenance', 'Maintenance')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='printhistory',
            name='print_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='my_app.printjob'),
        ),
    ]
